name: CI

on:  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install poetry
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      - name: Test
        run: make coverage
      - name: Report
          run: |
            export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
            ./cc-test-reporter upload-coverage
          env:
            CC_TEST_REPORTER_ID: f454552ee7437b3bcb435cd50272ebfb68fa2ebc52501833079921268e1cfd74
