name: CI

on:  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install poetry
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: f454552ee7437b3bcb435cd50272ebfb68fa2ebc52501833079921268e1cfd74
        with:
          coverageCommand:  make coverage
